
import listing1 from "../../../public/assets/images/listing/listing-1-1.jpg";
import listing2 from "../../../public/assets/images/listing/listing-1-2.jpg";
import listing3 from "../../../public/assets/images/listing/listing-1-3.jpg";
import listing4 from "../../../public/assets/images/listing/listing-1-4.jpg";
import listing5 from "../../../public/assets/images/listing/listing-1-5.jpg";
import listing6 from "../../../public/assets/images/listing/listing-1-6.jpg";
import img1 from "../../../public/assets/images/listing/listing-2-1.jpg";
import img2 from "../../../public/assets/images/listing/listing-2-2.jpg";
import img3 from "../../../public/assets/images/listing/listing-2-3.jpg";
import img4 from "../../../public/assets/images/listing/listing-2-4.jpg";
import img5 from "../../../public/assets/images/listing/listing-2-5.jpg";
import img6 from "../../../public/assets/images/listing/listing-2-6.jpg";
import img7 from "../../../public/assets/images/listing/listing-2-7.jpg";
import img8 from "../../../public/assets/images/listing/listing-2-8.jpg";
import car1 from '../../../public/assets/images/listing/listing-3-1.jpg';
import car2 from '../../../public/assets/images/listing/listing-3-2.jpg';
import car3 from '../../../public/assets/images/listing/listing-3-3.jpg';
import car4 from '../../../public/assets/images/listing/listing-3-4.jpg';
import car5 from '../../../public/assets/images/listing/listing-3-5.jpg';
import car6 from '../../../public/assets/images/listing/listing-1-6.jpg';

import type { CarItemTwo, ListingItem, ListingThreeItem } from "./listType";

export const listingData: ListingItem[] = [
    {
        id: 1,
        image: listing1,
        brand: "Acura",
        title: "Acura Sport Version",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 2,
        image: listing2,
        brand: "Kia Soul",
        title: "Kia Soul 2025",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 3,
        image: listing3,
        brand: "Audi",
        title: "Audi A3 2025 New",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 4,
        image: listing4,
        brand: "Ferrari",
        title: "Ferrari 458 MM Speciale",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 5,
        image: listing5,
        brand: "Acura",
        title: "Audi Sport Version",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 6,
        image: listing6,
        brand: "Toyota",
        title: "Toyota Tacoma 4WD",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 7,
        image: listing2,
        brand: "Honda",
        title: "Kia Soul 2025",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 8,
        image: listing3,
        brand: "Audi",
        title: "Audi A3 2025 New",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 9,
        image: listing4,
        brand: "Ferrari",
        title: "Ferrari 458 MM Speciale",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 10,
        image: listing4,
        brand: "Ferrari",
        title: "Ferrari 458 MM Speciale",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 11,
        image: listing5,
        brand: "Acura",
        title: "Audi Sport Version",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 12,
        image: listing6,
        brand: "Toyota",
        title: "Toyota Tacoma 4WD",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 13,
        image: listing2,
        brand: "Honda",
        title: "Kia Soul 2025",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 14,
        image: listing4,
        brand: "Ferrari",
        title: "Ferrari 458 MM Speciale",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 15,
        image: listing5,
        brand: "Acura",
        title: "Audi Sport Version",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 16,
        image: listing6,
        brand: "Toyota",
        title: "Toyota Tacoma 4WD",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 17,
        image: listing2,
        brand: "Honda",
        title: "Kia Soul 2025",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    }, {
        id: 18,
        image: listing6,
        brand: "Toyota",
        title: "Toyota Tacoma 4WD",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
    {
        id: 19,
        image: listing2,
        brand: "Honda",
        title: "Kia Soul 2025",
        transmission: "Manual",
        mileage: "25 KM",
        fuel: "Diesel",
        package: "Basic",
        minAge: "25",
        persons: "5",
        pricePerDay: 100,
        link: "/listing-single",
    },
];


export const carListTwo: CarItemTwo[] = [
    {
        id: 1,
        title: "Tesla S-Line Upon",
        category: "economy",
        price: "$180.00 /day",
        image: img1,
        link: "/inner/listing-single",
    },
    {
        id: 2,
        title: "Tesla S-Line Upon",
        category: "economy",
        price: "$180.00 /day",
        image: img2,
        link: "/inner/listing-single",
    },
    {
        id: 3,
        title: "BMW 640 XI Gran",
        category: "economy",
        price: "$180.00 /day",
        image: img3,
        link: "/inner/listing-single",
    },
    {
        id: 4,
        title: "Maserati Ghibli SQ4",
        category: "economy",
        price: "$180.00 /day",
        image: img4,
        link: "/inner/listing-single",
    },
    {
        id: 5,
        title: "Audi A4 1.8 TFSI",
        category: "economy",
        price: "$180.00 /day",
        image: img5,
        link: "/inner/listing-single",
    },
    {
        id: 6,
        title: "BMW Sports Car",
        category: "economy",
        price: "$180.00 /day",
        image: img6,
        link: "/inner/listing-single",
    },
    {
        id: 7,
        title: "Yellow Ferrari 458",
        category: "economy",
        price: "$180.00 /day",
        image: img7,
        link: "/inner/listing-single",
    },
    {
        id: 8,
        title: "Toyota Innova Crysta",
        category: "economy",
        price: "$180.00 /day",
        image: img8,
        link: "/inner/listing-single",
    },
];

// Data
export const listingThreeData: ListingThreeItem[] = [
    {
        id: 1,
        image: car1,
        brand: 'Acura',
        title: 'Acura Sport Version',
        price: 100,
        metaOne: [
            { icon: 'icon-manual', text: 'Manual' },
            { icon: 'icon-mileage', text: '25 KM' },
            { icon: 'icon-fuel-type', text: 'Diesel' },
        ],
        metaTwo: [
            { icon: 'icon-test-drive', text: 'Basic' },
            { icon: 'icon-avatar', text: 'Age 25' },
            { icon: 'icon-in-person', text: '5 Persons' },
        ],
    },
    {
        id: 2,
        image: car2,
        brand: 'Acura',
        title: 'Kia Soul 2025',
        price: 100,
        metaOne: [
            { icon: 'icon-manual', text: 'Manual' },
            { icon: 'icon-mileage', text: '25 KM' },
            { icon: 'icon-fuel-type', text: 'Diesel' },
        ],
        metaTwo: [
            { icon: 'icon-test-drive', text: 'Basic' },
            { icon: 'icon-avatar', text: 'Age 25' },
            { icon: 'icon-in-person', text: '5 Persons' },
        ],
    },
    {
        id: 3,
        image: car3,
        brand: 'Acura',
        title: 'Audi A3 2025 New',
        price: 100,
        metaOne: [
            { icon: 'icon-manual', text: 'Manual' },
            { icon: 'icon-mileage', text: '25 KM' },
            { icon: 'icon-fuel-type', text: 'Diesel' },
        ],
        metaTwo: [
            { icon: 'icon-test-drive', text: 'Basic' },
            { icon: 'icon-avatar', text: 'Age 25' },
            { icon: 'icon-in-person', text: '5 Persons' },
        ],
    },
    {
        id: 4,
        image: car4,
        brand: 'Acura',
        title: 'Ferrari 458 MM Speciale',
        price: 100,
        metaOne: [
            { icon: 'icon-manual', text: 'Manual' },
            { icon: 'icon-mileage', text: '25 KM' },
            { icon: 'icon-fuel-type', text: 'Diesel' },
        ],
        metaTwo: [
            { icon: 'icon-test-drive', text: 'Basic' },
            { icon: 'icon-avatar', text: 'Age 25' },
            { icon: 'icon-in-person', text: '5 Persons' },
        ],
    },
    {
        id: 5,
        image: car5,
        brand: 'Acura',
        title: 'Audi Sport Version',
        price: 100,
        metaOne: [
            { icon: 'icon-manual', text: 'Manual' },
            { icon: 'icon-mileage', text: '25 KM' },
            { icon: 'icon-fuel-type', text: 'Diesel' },
        ],
        metaTwo: [
            { icon: 'icon-test-drive', text: 'Basic' },
            { icon: 'icon-avatar', text: 'Age 25' },
            { icon: 'icon-in-person', text: '5 Persons' },
        ],
    },
    {
        id: 6,
        image: car6,
        brand: 'Acura',
        title: 'Toyota Tacoma 4WD',
        price: 100,
        metaOne: [
            { icon: 'icon-manual', text: 'Manual' },
            { icon: 'icon-mileage', text: '25 KM' },
            { icon: 'icon-fuel-type', text: 'Diesel' },
        ],
        metaTwo: [
            { icon: 'icon-test-drive', text: 'Basic' },
            { icon: 'icon-avatar', text: 'Age 25' },
            { icon: 'icon-in-person', text: '5 Persons' },
        ],
    },
    {
        id: 7,
        image: car1,
        brand: 'Acura',
        title: 'Acura Sport Version',
        price: 100,
        metaOne: [
            { icon: 'icon-manual', text: 'Manual' },
            { icon: 'icon-mileage', text: '25 KM' },
            { icon: 'icon-fuel-type', text: 'Diesel' },
        ],
        metaTwo: [
            { icon: 'icon-test-drive', text: 'Basic' },
            { icon: 'icon-avatar', text: 'Age 25' },
            { icon: 'icon-in-person', text: '5 Persons' },
        ],
    },
    {
        id: 8,
        image: car2,
        brand: 'Acura',
        title: 'Kia Soul 2025',
        price: 100,
        metaOne: [
            { icon: 'icon-manual', text: 'Manual' },
            { icon: 'icon-mileage', text: '25 KM' },
            { icon: 'icon-fuel-type', text: 'Diesel' },
        ],
        metaTwo: [
            { icon: 'icon-test-drive', text: 'Basic' },
            { icon: 'icon-avatar', text: 'Age 25' },
            { icon: 'icon-in-person', text: '5 Persons' },
        ],
    },
    {
        id: 9,
        image: car3,
        brand: 'Acura',
        title: 'Audi A3 2025 New',
        price: 100,
        metaOne: [
            { icon: 'icon-manual', text: 'Manual' },
            { icon: 'icon-mileage', text: '25 KM' },
            { icon: 'icon-fuel-type', text: 'Diesel' },
        ],
        metaTwo: [
            { icon: 'icon-test-drive', text: 'Basic' },
            { icon: 'icon-avatar', text: 'Age 25' },
            { icon: 'icon-in-person', text: '5 Persons' },
        ],
    },
    {
        id: 10,
        image: car4,
        brand: 'Acura',
        title: 'Ferrari 458 MM Speciale',
        price: 100,
        metaOne: [
            { icon: 'icon-manual', text: 'Manual' },
            { icon: 'icon-mileage', text: '25 KM' },
            { icon: 'icon-fuel-type', text: 'Diesel' },
        ],
        metaTwo: [
            { icon: 'icon-test-drive', text: 'Basic' },
            { icon: 'icon-avatar', text: 'Age 25' },
            { icon: 'icon-in-person', text: '5 Persons' },
        ],
    },
    {
        id: 11,
        image: car5,
        brand: 'Acura',
        title: 'Audi Sport Version',
        price: 100,
        metaOne: [
            { icon: 'icon-manual', text: 'Manual' },
            { icon: 'icon-mileage', text: '25 KM' },
            { icon: 'icon-fuel-type', text: 'Diesel' },
        ],
        metaTwo: [
            { icon: 'icon-test-drive', text: 'Basic' },
            { icon: 'icon-avatar', text: 'Age 25' },
            { icon: 'icon-in-person', text: '5 Persons' },
        ],
    },
    {
        id: 12,
        image: car6,
        brand: 'Acura',
        title: 'Toyota Tacoma 4WD',
        price: 100,
        metaOne: [
            { icon: 'icon-manual', text: 'Manual' },
            { icon: 'icon-mileage', text: '25 KM' },
            { icon: 'icon-fuel-type', text: 'Diesel' },
        ],
        metaTwo: [
            { icon: 'icon-test-drive', text: 'Basic' },
            { icon: 'icon-avatar', text: 'Age 25' },
            { icon: 'icon-in-person', text: '5 Persons' },
        ],
    },
];


